---
title: "Research Work"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Exploring Linkage between Human Capital and Economic Growth: A Look into 141 Panels of Developing and Developed Countriess
As factors of production, human capital is defined in its both health and educational
dimensions incorporating the qualitative and quantitative aspects. Using a panel of 141
countries (93 developing and 48 developed); we attempted to explore and compare the
impact of human capital on economic growth in different development stages. For
estimation, System Generalized Methods of Moments (SGMM) is employed for the
period of 1980-2008. Findings reveal that all aspects of human capital positively
influence growth in developing countries, especially life expectancy gain, which may be
explained by the demographic transition these countries are going through. However,
the scenario is different for developed countries where increased life expectancy posits
a drag on economic growth, probably because of the increasing aging population and
dependency ratio. Only when life expectancy is omitted, health expenditure, along with
other educational measures of human capitals, help in sustaining growth in developed
countries.

## Tourism Development and Economic Growth in Bangladesh: New Evidence from Nonlinear Autoregressive Distributed Lag
We examine the long-run relationship between tourism development and economic growth using the Nonlinear Autoregressive Distributed Lag (NARDL) model for Bangladesh using annual data from 1980 to 2016. We find an asymmetric relationship between tourism and Bangladesh’s economy since a 1% increase in tourism receipt increases economic growth by about 0.19%. On the contrary, due to a 1% decline in the tourism receipt, economic growth will decrease by about 0.66%. So, the decline in tourism receipt will have a higher negative impact on economic growth than the increase in the tourism receipt in Bangladesh, which result is important for current pandemic situation in tourism due to Covid-19. We also reveal that the impact of positive change in the tourism revenue on GDP stabilizes around 8 years; however, an adverse change on GDP does not stabilize in 15 years. We recommend that a systematic allocation of resources is required to promote and stimulate the tourism industry in Bangladesh for a favourable impact on the country’s long-run economic development.


## Impact of Covid-19 on Dhaka Stock Exchange: An Interrupted Time Series Analysis
The modern economy is down to its knees due to the unprecedented event caused by Covid-19.
The capital market of Bangladesh had also encountered significant volatility due to this pandemic.
We employ the Interrupted Time Series (ITS) analysis, a robust quasi-experimental design, to
find out if there is a structural break in Bangladesh's capital market, initiated by Covid-19. To our
knowledge, this paper is the very first instance of using the ITS method for Bangladesh to
investigate the Covid-19 effect on the financial sector. This paper used five daily market summary
data: total trade of stocks, the total value of the traded stocks, total volume of the stocks, total
market capital and DSEX index from October 1, 2018 to October 29, 2020 to quantify the impact
of Covid-19. This study's results are very surprising as total trade, total value, and total volume
of stock have a significant positive level shift, and market capital and DSEX index have a
significant positive trend shift after the Covid-19 lockdown. These results can be explained by
the optimistic traders who gained confidence from the government's stimulus package, a recordbreaking number in remittance and reserve, and a relatively higher economic growth forecast than
Bangladesh's neighboring countries.

